# ~/.config/alacritty/alacritty.yml
window:
  opacity: 0.5
  decorations: full
  padding:
    x: 8
    y: 8
  dynamic_padding: true

font:
  normal:
    family: JetBrainsMono Nerd Font
    style: Regular
  bold:
    family: JetBrainsMono Nerd Font
    style: Bold
  italic:
    family: JetBrainsMono Nerd Font
    style: Italic
  size: 12.0

colors:
  primary:
    background: '0x0f0f17'
    foreground: '0xd0d0d0'
  cursor:
    text: '0x0f0f17'
    cursor: '0x00ffe0'
  selection:
    text: '0x0f0f17'
    background: '0x00ffe0'
  normal:
    black:   '0x1a1b26'
    red:     '0xf7768e'
    green:   '0x9ece6a'
    yellow:  '0xe0af68'
    blue:    '0x7aa2f7'
    magenta: '0xad8ee6'
    cyan:    '0x449dab'
    white:   '0xc0caf5'
  bright:
    black:   '0x414868'
    red:     '0xf7768e'
    green:   '0x9ece6a'
    yellow:  '0xe0af68'
    blue:    '0x7aa2f7'
    magenta: '0xad8ee6'
    cyan:    '0x449dab'
    white:   '0xffffff'

cursor:
  style: Beam
  unfocused_hollow: true

scrolling:
  history: 10000
  multiplier: 3

key_bindings:
  - { key: V,        mods: Control|Shift, action: Paste }
  - { key: C,        mods: Control|Shift, action: Copy }
  - { key: N,        mods: Control|Shift, action: SpawnNewInstance }
